In [1]:
from fairseq.models.transformer_lm import TransformerLanguageModel
from torch.utils.data import DataLoader
import torch 
import numpy as np
import os

os.environ["TRUST_REMOTE_CODE"] = "True"
local_rank = 0
device = "cuda:" + str(local_rank) if torch.cuda.is_available() else "cpu"
torch.cuda.set_device(device)
device_type = "cuda" if device.startswith("cuda") else "cpu"

#Load Pretrained Model
fairseq_model = TransformerLanguageModel.from_pretrained('/base-vol-2/fairseq/models/adaptive_lm_wiki103.v2/', 'model.pt')

2024-07-25 18:36:12 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-07-25 18:36:13 | INFO | fairseq.file_utils | loading archive file /base-vol-2/fairseq/models/adaptive_lm_wiki103.v2/
/home/jovyan/fairseq/fairseq/checkpoint_utils.py:340: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=

In [2]:
model = fairseq_model.models[0].to(device)
model.eval()
print(model)

TransformerLanguageModel(
  (decoder): TransformerDecoder(
    (dropout_module): FairseqDropout()
    (embed_tokens): AdaptiveInput(
      (embeddings): ModuleList(
        (0): Sequential(
          (0): Embedding(20000, 1024, padding_idx=1)
          (1): Linear(in_features=1024, out_features=1024, bias=False)
        )
        (1): Sequential(
          (0): Embedding(40000, 256)
          (1): Linear(in_features=256, out_features=1024, bias=False)
        )
        (2): Sequential(
          (0): Embedding(207744, 64)
          (1): Linear(in_features=64, out_features=1024, bias=False)
        )
      )
    )
    (embed_positions): SinusoidalPositionalEmbedding()
    (layers): ModuleList(
      (0-15): 16 x TransformerDecoderLayerBase(
        (dropout_module): FairseqDropout()
        (self_attn): MultiheadAttention(
          (dropout_module): FairseqDropout()
          (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
          (v_proj): Linear(in_features=1024, o

In [3]:
#COMPARE EMBEDDING LAYERS
torch.manual_seed(0)
x = torch.randint(0, 270000, (4, 16)).to(device)
print(x)
y = model.decoder.embed_tokens(x)
print(y)

tensor([[ 36044, 148239, 194933, 263760,  88963, 158379, 165427, 128503,  53497,
          55683, 114101, 126866, 222756, 261399, 185878,  40376],
        [ 70056,  59868, 138794,  96033,  53126, 108119,  76391,  36254,  12824,
          37841, 197269, 200969, 267549,  15480, 267481, 177012],
        [167363, 195360, 194995, 200085,  97822, 161999, 143711, 196288,  43778,
         221043, 119896,  85489, 238771, 103757,  27283,  35395],
        [114782,  83671, 109840,  95969,  97673,  40441,  32111, 139280,  51503,
         189706,  39476, 188327,  97699,  11326, 258363,  99474]],
       device='cuda:0')
tensor([[[-3.4055e-02, -2.3982e-02,  1.4842e-02,  ...,  3.7100e-02,
          -3.4246e-02,  4.8659e-02],
         [-1.1439e-02, -7.6053e-02,  2.5387e-02,  ...,  1.9912e-02,
           5.7698e-02,  8.2409e-02],
         [ 3.8668e-02,  4.4477e-03, -4.3590e-02,  ..., -6.0638e-02,
          -9.2839e-02,  1.1963e-01],
         ...,
         [-5.6529e-03,  3.5787e-03, -7.8591e-02,  ...,  3.

In [8]:
print(model.decoder.adaptive_softmax.tail[0][2].weight)

Parameter containing:
tensor([[-0.0146, -0.0676,  0.0558,  ..., -0.0039,  0.0562, -0.0482],
        [ 0.0254,  0.1409,  0.1180,  ..., -0.0151,  0.0250,  0.0528],
        [-0.0348, -0.0837,  0.0565,  ..., -0.0178,  0.0721, -0.0120],
        ...,
        [ 0.0138, -0.0245,  0.0538,  ...,  0.0685, -0.0158, -0.1499],
        [ 0.0312,  0.0453, -0.0673,  ...,  0.0781,  0.0562,  0.0264],
        [-0.0180,  0.0482, -0.0445,  ..., -0.0019,  0.1675, -0.0756]],
       device='cuda:0', requires_grad=True)


In [6]:
targets = x 
targets = targets.view(-1)
inputs = y
output = model.decoder.adaptive_softmax(inputs,targets)
print(output.size())
print(output[0,0,targets[0]])


AttributeError: 'tuple' object has no attribute 'size'